### ISSUE TITLE
Failed to execute script eidreader

### ISSUE THREAD

**Issue by Mannesman** [lino-framework/eidreader#13]
Hello,

Since a week or so, we get a "Fatal Error!" when calling eidreader.exe from Chrome and Edge. In Firefox, everything works as it used to.

We installed following the instructions on https://eidreader.lino-framework.org/install.html;

[HKEY_CLASSES_ROOT\beid]
@="URL: beid Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\beid\shell]

[HKEY_CLASSES_ROOT\beid\shell\open]

[HKEY_CLASSES_ROOT\beid\shell\open\command]
@="C:\\eidreader\\eidreader.exe %1"

We get the same error on the testing site  "https://weleup1.mylino.net/" in Chrome and Edge, though not in Firefox.

We send our request as follows;

> beid://https//xxxxxx.xxxx/receivedata.php?id=123456&date=2024-10-24
Could it be that Chrome or Edge removes the extra ":" behind "https" in the url? 

Thanks for checking and letting us know how to possibly resolve this.

Kristof

**Comment by lsaffre** [comment]
Hi Kristof. Hm, eidreader itself does not emit any error with the message "Fatal Error". When I call "eidreader beid://https//xxxxxx.xxxx/receivedata.php?id=123456&date=2024-10-24" from the command line, I get indeed a traceback saying "requests.exceptions.InvalidSchema: No connection adapters were found for 'beid://https//xxxxxx.xxxx/receivedata.php?id=123456'". And I would say that this error message is correct. It's possible that Chrome hides the full traceback and summarizes it as "Fatal Error". But at the moment we don't even know whether Chrome actually did call it like this. What does your eidreader.log file say?

**Comment by Mannesman** [comment]
Hello Luc,

Google Chrome;
[2024-10-24 13:47:35,822] INFO POST data to beid://https//domein.be/receivedata.php?...
Then the fatal error and no more info in logfile

Firefox;
[2024-10-24 13:48:31,927] INFO POST data to https://domein.be/receivedata.php?...
[2024-10-24 13:48:32,248] INFO POST returned <Response [200]>

Please note in Chrome “beid:” is not removed from the URL.

We call eidreader in JS as follows, is that possibly causing the problem? Any ideas?

var myurl = “https://domein.be/receivedata.php”;
var paramstring = "?id="+ID+"&date="+datum;
myurl = myurl + paramstring;
location.href = "beid://" + myurl;

Mvg, Kristof

**Comment by lsaffre** [comment]
Hm, the JS code looks normal. I suggest to add a "console.warn(myurl)" and then look at the JS console in the browser.

Earlier in the eidreader log, even before the message "INFO POST data to"  there should also be a message  "INFO Invoked as". Report this too, please (for both browsers). I see that you don't specify the "-l" option in your registry, maybe you should add it:

```
[HKEY_CLASSES_ROOT\beid\shell\open\command]
@="C:\\eidreader\\eidreader.exe -l C:\\eidreader\\eidreader.log %1"

```

**Comment by Mannesman** [comment]
Hello Luc,

After digging around a bit, I found it to be a Chromium "feature";

https://docs.google.com/document/d/1LjxHl32fE4tCKugrK_PIso7mfXQVEeoD1wSnX2y0ZU8/edit?resourcekey=0-d1gP4X2sG7GPl9mlTeptIA&tab=t.0#heading=h.a67ulu2yrl9p

Doe you see a way to work around this without ?

**Comment by lsaffre** [comment]
Good research work, Kristof! I see no workaround without releasing a new version. eidreader actually just needs to unquote the given URL (and your JS code must quote it. Cross your fingers, I'm almost done with a version 1.0.8.

**Comment by lsaffre** [comment]
I released [version 1.0.8](https://eidreader.lino-framework.org/changes.html), so now in your JS code you can quote the URL (replace the second "://" with "%3A//").

I added two test cases in the [Don't read](https://eidreader.lino-framework.org/usage.html#don-t-read) section of the Usage page.

**Comment by lsaffre** [comment]
I hope this helps. @Mannesman please test it and close the ticket when your problem is fixed.

**Comment by Mannesman** [comment]
Hello, I will try to test over the weekend and report back.

**Comment by Mannesman** [comment]
Hello, I have limited experience in python, compiling to exe files etc... I fiddled with the code and succeeded in testing with the "%3A//" with positive results!

I tried compiling to exe, but that isn't working out. Would you please be so kind to compile a zip as in https://eidreader.lino-framework.org/dl/eidreader-1.0.6.zip ?

Thanks in advance.
Kristof

**Comment by lsaffre** [comment]
I have no Microsoft software under my roof, so I cannot compile a Windows executable zip file myself. But I now asked a friend to run the instructions on https://eidreader.lino-framework.org/build.html and send me the eidreader.zip file.

**Comment by Mannesman** [comment]
Eureka!

Creating the exe, and running the exe, resulted in following error;

> Traceback (most recent call last):
>   File "importlib\metadata\__init__.py", line 407, in from_name
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "eidreader.py", line 30, in <module>
>   File "importlib\metadata\__init__.py", line 987, in version
>   File "importlib\metadata\__init__.py", line 960, in distribution
>   File "importlib\metadata\__init__.py", line 409, in from_name
> importlib.metadata.PackageNotFoundError: No package metadata

I changed some code in eidreader.py as follows, recompiled and solved the mentioned exception;

```
#__version__ = importlib.metadata.version("eidreader")
__version__ = "1.0.8"
```
Not certain though if this has possible consequences somewhere else. As far as I can see it, this shouldn't cause other problems?

**Comment by lsaffre** [comment]
Indeed, importlib.metadata.version("eidreader") fails when eidreader is not installed (did you run "pip install -e ." after cloning the source code?). But whatever the reason, in order to avoid this problem I now changed the pyproject.toml to use dynamic versioning and removed the dependency from importlib.

**Comment by lsaffre** [comment]
> Not certain though if this has possible consequences somewhere else. As far as I can see it, this shouldn't cause other problems?

Your patch is a good solution and doesn't break anything. The pyproject.toml file is needed only when distributing the Python package on PyPI.
