### ISSUE TITLE
Issues with scheme handler on Mac OS

### ISSUE THREAD

**Issue by ghost** [lino-framework/eidreader#4]
Hello there,

I'm having issues with the scheme handler (beid://) on mac os.

Would there be another solution (maybe easier) to make it work ?

I've heard of :

[t1c-lib-js](https://github.com/Trust1Team/t1c-lib-js)

Thanks 👍

**Comment by lsaffre** [comment]
Yes, that might work. Actually the [eidreader and the web application](http://eidreader.lino-framework.org/usage.html#eidreader-and-the-web-application) section is just our way to integrate it. If you get it done using some other method, please change the documentation and submit a pull request.

**Comment by lsaffre** [comment]
This should be fixed after https://github.com/lino-framework/eidreader/commit/ef1f4a18ff40d42ce56ef05f303095b763bc90b9
