### ISSUE TITLE
Unable to get past below ING link

### ISSUE THREAD

**Issue by Bill7518** [lino-framework/eidreader#5]
1. Chrome plugin installed for eID
2. Went to ING.be
3. Logged in OK on ING.be
4. To go to the eID pages to update details, I am sent to this link: https://www.ing.be/nl/retail/Remote-eID?WT.mc_id=DE_redirect
5. Result: white screen, no reason for forwarding to pages needed on eID

![image](https://user-images.githubusercontent.com/61239327/74843152-6e6fc180-5323-11ea-8a11-e17b8568c364.png)

**Comment by lsaffre** [comment]
I don't see how this issue would be related to eidreader.
